### PR TITLE
Style Elixir function parameter variables

### PR DESCRIPTION
**Pull request by rgreenjr**
### Description of the Change

Support for capturing function parameter variables was [recently added to the Atom Elixir syntax](https://github.com/elixir-editors/language-elixir/pull/98). This pull request uses these new captures to style Elixir function parameter variables. It sets their font style to `italic` and color to `@hue-6`. This matches the styling used by Sublime Text and TextMate.

Here's before:

example1

And here's after:

example

### Alternate Designs

None

### Benefits

Elixir supports function pattern matching. This change makes it easier to differentiate function parameter variables from other function parameters. See the image above for several examples. 

Both Sublime Text and TextMate apply a similar styling to Elixir function parameter variables.

### Possible Drawbacks

None

### Applicable Issues

None

### CODE REVIEW

**Comment by rgreenjr** [comment]
I'm happy to provide additional information to prepare this to be merged into master.

Just let me know, thanks. 👍

**Comment by rsese** [comment]
Sorry about that @rgreenjr - the person who might normally review this is OoO for a while.  I can't make any promises, but I'll mention this to the team for you.

If it's not too much trouble, could you add a "before" image to your issue body?

**Comment by rgreenjr** [comment]
Hi @rsese, thanks for the quick reply. 

I realized after I posted my message that I probably should have posted a "before" image to make reviewing the changes easier. Sorry about that, I'll update the issue body right now.

Thanks again.

**Comment by rsese** [comment]
np thanks for adding the before image @rgreenjr :bow:

I asked the team about your PR and we agreed that it's best if @simurai takes a look when he gets back.

/cc @simurai to get this on your list :v:

**Comment by rgreenjr** [comment]
Thanks @rsese. I completely understand.

**Comment by rgreenjr** [comment]
Hi @simurai – Please let me know if you need any additional information. Thanks! 👍

**Pull request merged**
