### PR TITLE
Highlight keyword operators, fixed #44

### LINKED ISSUE #44: Operators aren't highlighted
Currently operators like `+`,`!==`, `||`, `typeof` and `new` aren't highlighted in JavaScript.

screen shot 2015-09-07 at 16 22 56

Is this intended behaviour?

### PR DESCRIPTION
**Pull request by livelazily**

### CODE REVIEW

**Comment by simurai** [comment]
@livelazily Thanks.

Before:

screen shot 2016-02-04 at 10 42 36 am

After:

screen shot 2016-02-04 at 10 42 19 am

1. The `javascript.less` file needs to be imported from `index.less`, maybe after `java.less`: https://github.com/atom/one-dark-syntax/blob/master/index.less#L13
2. Wow.. That Less code is so advanced.. :flushed: Would you be ok to write it a bit simpler? Maybe something like this:

```less
.source.js {
  .keyword.operator {
    &.delete,
    &.in,
    &.of,
    &.instanceof,
    &.new,
    &.typeof,
    &.void {
      color: @syntax-color-keyword;
    }
  }
}
```

It is less elegant, but maybe easier to understand.

**Comment by livelazily** [comment]
@simurai Please review again.

**Comment by 50Wliu** [comment]
Perhaps the "regular" operators should also receive a different color to help them stand out?

**Comment by livelazily** [comment]
@50Wliu see https://github.com/atom/one-dark-syntax/issues/44#issuecomment-162355498

**Comment by simurai** [comment]
> Perhaps the "regular" operators should also receive a different color to help them stand out?

Here the same example from #44:

Before:

screen shot 2015-12-06 at 2 20 22 pm

Only keywords (this PR)

screen shot 2016-02-04 at 11 23 48 am

All operators:

screen shot 2015-12-06 at 2 03 25 pm

What do you think? I'm open to both, but if I would have to pick, it's "Only keywords". Colored `=` just feels a bit too much.

**Comment by 50Wliu** [comment]
I was actually suggesting a different color than purple (blue?  green?  I don't know) - not sure if that's feasible or not though with the base16 palette.

**Comment by simurai** [comment]
`cyan`? Since it's close to the neutral grey, but still a little color.

screen shot 2016-02-04 at 11 39 36 am

**Comment by simurai** [comment]
Ok, let's merge this and I'll add the `cyan` after.

@livelazily thanks for the PR.

**Pull request merged**
