### PR TITLE
Revert colors to v0.5.0

### LINKED ISSUE #23: Improve contrast of text
(1) The background should be much closer to black

(2) The text should be high in brightness (e.g. default text should be white/#fff)

This is a large usability concern.  Without high contrast, text is much more difficult to read.

Comparison to Sublime:

Atom:
screen shot 2015-04-15 at 10 39 42 am

Sublime:
screen shot 2015-04-15 at 10 39 47 am

### PR DESCRIPTION
**Pull request by simurai**
This PR reverts the colors to the previous version. Closes #23

### CODE REVIEW

**Comment by philipgiuliani** [comment]
:sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob:

**Comment by simurai** [comment]
@philipgiuliani You missed the discussion: #23 :disappointed:

There is still the [sm-high-contrast](https://github.com/atom/one-dark-syntax/tree/sm-high-contrast) branch if you wanna clone and `apm link` it.

And hopefully there will be an option in the settings one day to change it.

**Comment by philipgiuliani** [comment]
Yes unfortunately :cry: Why should somebody search an issue if everything is (was) perfect.. :)
Thanks for the branch :+1: The high contrast branch is much better for my eyes. Option would be amazing! Isn't that possible currently?

**Comment by simurai** [comment]
> Option would be amazing! Isn't that possible currently?

Not officially, but maybe like in @coopermaruyama comment: https://github.com/atom/atom/issues/5903#issuecomment-106163826

> Lets see what people say after the next release.. :)

:weary:

**Pull request merged**
